# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Threepctl < Formula
  desc "A CLI for managing the Threeport platform."
  homepage "https://github.com/threeport/threepctl"
  version "1.0.5"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/threeport/threepctl/releases/download/v1.0.5/threepctl_v1.0.5_macOS_x86_64.tar.gz"
      sha256 "865052ad52f80c60d4bf1f2cf8598521927a2741107b9ba69fbdfe1db9800f66"

      def install
        bin.install "threepctl"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/threeport/threepctl/releases/download/v1.0.5/threepctl_v1.0.5_macOS_arm64.tar.gz"
      sha256 "4b1835d3b53c7d62360f5d06040e471b262935189ca1cebd23cd93c4f81c408a"

      def install
        bin.install "threepctl"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/threeport/threepctl/releases/download/v1.0.5/threepctl_v1.0.5_Linux_x86_64.tar.gz"
      sha256 "aef4c9fc531ce62d00a84440e0c8dfc21140efe57b7a1e0cd0f7ad73137d30a3"

      def install
        bin.install "threepctl"
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/threeport/threepctl/releases/download/v1.0.5/threepctl_v1.0.5_Linux_arm.tar.gz"
      sha256 "6b42c08464bb36813d871d02aa955acd54aa80fe9265a377e6d50d42576bbdb2"

      def install
        bin.install "threepctl"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/threeport/threepctl/releases/download/v1.0.5/threepctl_v1.0.5_Linux_arm64.tar.gz"
      sha256 "9833d7c80b700f15253c3cd03ebcb9bba3ed2062479afe4c0ef501e0174a25f2"

      def install
        bin.install "threepctl"
      end
    end
  end

  test do
    system "#{bin}/threepctl version"
  end
end
