# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Threepctl < Formula
  desc "A CLI for managing the Threeport platform."
  homepage "https://github.com/threeport/threepctl"
  version "1.0.4"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/threeport/threepctl/releases/download/v1.0.4/threepctl_v1.0.4_macOS_arm64.tar.gz"
      sha256 "34c40e2d3f6924d566261b9108070bb6836e40e078ba7680a3583c27941ecdac"

      def install
        bin.install "threepctl"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/threeport/threepctl/releases/download/v1.0.4/threepctl_v1.0.4_macOS_x86_64.tar.gz"
      sha256 "ca7d851a5b3db30e13cfb1612e015dce4f83596c518785babf1040d92d8fa127"

      def install
        bin.install "threepctl"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/threeport/threepctl/releases/download/v1.0.4/threepctl_v1.0.4_Linux_x86_64.tar.gz"
      sha256 "c175d25212f46ca1b7e5fcea2cd7677d725372e7536ace373a569ab9da3dd74d"

      def install
        bin.install "threepctl"
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/threeport/threepctl/releases/download/v1.0.4/threepctl_v1.0.4_Linux_arm.tar.gz"
      sha256 "8b78921996a1517ff4ff05a93895fc04fc68707eaac06b001ae0cc60eddf8795"

      def install
        bin.install "threepctl"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/threeport/threepctl/releases/download/v1.0.4/threepctl_v1.0.4_Linux_arm64.tar.gz"
      sha256 "8c10aca1db37274c65542c008cc56b7d98d803ef5675bbe6ce951ab1cb22508b"

      def install
        bin.install "threepctl"
      end
    end
  end

  test do
    system "#{bin}/threepctl version"
  end
end
