# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Tptctl < Formula
  desc "A CLI for managing workloads on Threeport."
  homepage "https://github.com/threeport/tptctl"
  version "0.0.5"
  license "MIT"

  depends_on "docker"
  depends_on "kubectl"
  depends_on "kind"
  depends_on "wget"
  depends_on "jq"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/threeport/tptctl/releases/download/v0.0.5/tptctl_v0.0.5_Darwin_arm64.tar.gz"
      sha256 "00fa40f31ccf008a6f53da84d7e908fdb0e018ee6c7fae62ab6d0a3c3ad095fd"

      def install
        bin.install "tptctl"
        bash_completion.install "completions/tptctl.bash" => "tptctl"
        zsh_completion.install "completions/tptctl.zsh" => "_tptctl"
        fish_completion.install "completions/tptctl.fish"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/threeport/tptctl/releases/download/v0.0.5/tptctl_v0.0.5_Darwin_x86_64.tar.gz"
      sha256 "9ce14a345568172195fd49b5bb5915c1cfbc3132ed0a7114aa549c9a4bc19df8"

      def install
        bin.install "tptctl"
        bash_completion.install "completions/tptctl.bash" => "tptctl"
        zsh_completion.install "completions/tptctl.zsh" => "_tptctl"
        fish_completion.install "completions/tptctl.fish"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/threeport/tptctl/releases/download/v0.0.5/tptctl_v0.0.5_Linux_arm64.tar.gz"
      sha256 "a8397166502a80bf7801f4ecda0987377aff7fe244ed6d1350025d375c9b1f31"

      def install
        bin.install "tptctl"
        bash_completion.install "completions/tptctl.bash" => "tptctl"
        zsh_completion.install "completions/tptctl.zsh" => "_tptctl"
        fish_completion.install "completions/tptctl.fish"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/threeport/tptctl/releases/download/v0.0.5/tptctl_v0.0.5_Linux_x86_64.tar.gz"
      sha256 "aaa85c771ac5bfc3b004e076036c5c1175c8f4e665b1998406dfbd101c2cc479"

      def install
        bin.install "tptctl"
        bash_completion.install "completions/tptctl.bash" => "tptctl"
        zsh_completion.install "completions/tptctl.zsh" => "_tptctl"
        fish_completion.install "completions/tptctl.fish"
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/threeport/tptctl/releases/download/v0.0.5/tptctl_v0.0.5_Linux_arm.tar.gz"
      sha256 "cad4d01e1571253242469b61bbec22944cb02ed6f1752599b79e62c813f9a682"

      def install
        bin.install "tptctl"
        bash_completion.install "completions/tptctl.bash" => "tptctl"
        zsh_completion.install "completions/tptctl.zsh" => "_tptctl"
        fish_completion.install "completions/tptctl.fish"
      end
    end
  end

  test do
    system "#{bin}/tptctl version"
  end
end
