# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Tptctl < Formula
  desc "A CLI for managing workloads on Threeport."
  homepage "https://github.com/threeport/tptctl"
  version "0.0.3"
  license "MIT"

  depends_on "docker"
  depends_on "kubectl"
  depends_on "kind"
  depends_on "wget"
  depends_on "jq"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/threeport/tptctl/releases/download/v0.0.3/tptctl_v0.0.3_Darwin_arm64.tar.gz"
      sha256 "69d7973f52894d63b9406cd33d6c413bba285645f2d9112c39369c9c0a00540a"

      def install
        bin.install "tptctl"
        bash_completion.install "completions/tptctl.bash" => "tptctl"
        zsh_completion.install "completions/tptctl.zsh" => "_tptctl"
        fish_completion.install "completions/tptctl.fish"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/threeport/tptctl/releases/download/v0.0.3/tptctl_v0.0.3_Darwin_x86_64.tar.gz"
      sha256 "e74a2aa28a1cc39cbf494ecd33ba6b599dd94130441d25ac6ab5770d59359041"

      def install
        bin.install "tptctl"
        bash_completion.install "completions/tptctl.bash" => "tptctl"
        zsh_completion.install "completions/tptctl.zsh" => "_tptctl"
        fish_completion.install "completions/tptctl.fish"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/threeport/tptctl/releases/download/v0.0.3/tptctl_v0.0.3_Linux_x86_64.tar.gz"
      sha256 "2ab84b11fa16a20d9513d0933471190886a7c18188e4357ad92f5e5ede7408e4"

      def install
        bin.install "tptctl"
        bash_completion.install "completions/tptctl.bash" => "tptctl"
        zsh_completion.install "completions/tptctl.zsh" => "_tptctl"
        fish_completion.install "completions/tptctl.fish"
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/threeport/tptctl/releases/download/v0.0.3/tptctl_v0.0.3_Linux_arm.tar.gz"
      sha256 "7d5f8a67e71ce7d6607973bb4c496f3f8ffadb5f8e211169e562892391362eda"

      def install
        bin.install "tptctl"
        bash_completion.install "completions/tptctl.bash" => "tptctl"
        zsh_completion.install "completions/tptctl.zsh" => "_tptctl"
        fish_completion.install "completions/tptctl.fish"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/threeport/tptctl/releases/download/v0.0.3/tptctl_v0.0.3_Linux_arm64.tar.gz"
      sha256 "67830f948527487fd502d299f9d0b4e62de0a4b203c29a90818c7592053b0c0e"

      def install
        bin.install "tptctl"
        bash_completion.install "completions/tptctl.bash" => "tptctl"
        zsh_completion.install "completions/tptctl.zsh" => "_tptctl"
        fish_completion.install "completions/tptctl.fish"
      end
    end
  end

  test do
    system "#{bin}/tptctl version"
  end
end
