# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Tptctl < Formula
  desc "A CLI for managing workloads on Threeport."
  homepage "https://github.com/threeport/tptctl"
  version "0.0.4"
  license "MIT"

  depends_on "docker"
  depends_on "kubectl"
  depends_on "kind"
  depends_on "wget"
  depends_on "jq"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/threeport/tptctl/releases/download/v0.0.4/tptctl_v0.0.4_Darwin_x86_64.tar.gz"
      sha256 "e190b1cadd4b05aec5e5f74a67aef9034386e7bcfa8533f5fb889fc11840f988"

      def install
        bin.install "tptctl"
        bash_completion.install "completions/tptctl.bash" => "tptctl"
        zsh_completion.install "completions/tptctl.zsh" => "_tptctl"
        fish_completion.install "completions/tptctl.fish"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/threeport/tptctl/releases/download/v0.0.4/tptctl_v0.0.4_Darwin_arm64.tar.gz"
      sha256 "3cd6ea9815721c748b3c135372297842ae0c084db8f1e1ddbb7d1003b966df27"

      def install
        bin.install "tptctl"
        bash_completion.install "completions/tptctl.bash" => "tptctl"
        zsh_completion.install "completions/tptctl.zsh" => "_tptctl"
        fish_completion.install "completions/tptctl.fish"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/threeport/tptctl/releases/download/v0.0.4/tptctl_v0.0.4_Linux_arm.tar.gz"
      sha256 "569249c26be94c1f303a6701a64bae9d55a8148b3efec4fb332166e75ba8cc9d"

      def install
        bin.install "tptctl"
        bash_completion.install "completions/tptctl.bash" => "tptctl"
        zsh_completion.install "completions/tptctl.zsh" => "_tptctl"
        fish_completion.install "completions/tptctl.fish"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/threeport/tptctl/releases/download/v0.0.4/tptctl_v0.0.4_Linux_arm64.tar.gz"
      sha256 "429c9ca75c1a55a488e355f5d7d2d515dddc6a87a792c08f1c0dda84fd16f158"

      def install
        bin.install "tptctl"
        bash_completion.install "completions/tptctl.bash" => "tptctl"
        zsh_completion.install "completions/tptctl.zsh" => "_tptctl"
        fish_completion.install "completions/tptctl.fish"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/threeport/tptctl/releases/download/v0.0.4/tptctl_v0.0.4_Linux_x86_64.tar.gz"
      sha256 "4981a4bd4584746ac892936dff84c9b495f6559f6b52930a495b375e4d52d2b1"

      def install
        bin.install "tptctl"
        bash_completion.install "completions/tptctl.bash" => "tptctl"
        zsh_completion.install "completions/tptctl.zsh" => "_tptctl"
        fish_completion.install "completions/tptctl.fish"
      end
    end
  end

  test do
    system "#{bin}/tptctl version"
  end
end
